// <auto-generated />
using System;
using MarketPrice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPrice.Migrations
{
    [DbContext(typeof(MarketPriceDbContext))]
    [Migration("20251114115051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocationUser", b =>
                {
                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LocationUser");
                });

            modelBuilder.Entity("MarketPrice.Models.AccountType", b =>
                {
                    b.Property<int>("AccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountTypeId"));

                    b.Property<string>("AccountTypeCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("AccountTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountTypeId");

                    b.ToTable("AccountTypes", t =>
                        {
                            t.HasCheckConstraint("CK_AccountTypes_AccountTypeName_Enum", "[AccountTypeName] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.Commodity", b =>
                {
                    b.Property<Guid>("CommodityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommodityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommodityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CommodityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short?>("LotSize")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ShelfLifeInDays")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommodityId");

                    b.HasIndex("CommodityTypeId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("MarketPrice.Models.CommodityGroup", b =>
                {
                    b.Property<Guid>("CommodityGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommodityGroupName")
                        .HasColumnType("int");

                    b.HasKey("CommodityGroupId");

                    b.ToTable("CommodityGroups", t =>
                        {
                            t.HasCheckConstraint("CK_CommodityGroups_CommodityGroupName_Enum", "[CommodityGroupName] BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.CommodityType", b =>
                {
                    b.Property<Guid>("CommodityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommodityGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommodityTypeName")
                        .HasColumnType("int");

                    b.Property<Guid>("DefaultUnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommodityTypeId");

                    b.HasIndex("CommodityGroupId");

                    b.HasIndex("DefaultUnitOfMeasureId");

                    b.ToTable("CommodityTypes", t =>
                        {
                            t.HasCheckConstraint("CK_CommodityTypes_CommodityTypeName_Enum", "[CommodityTypeName] BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.DeliveryDetail", b =>
                {
                    b.Property<Guid>("DeliveryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeliverable")
                        .HasColumnType("bit");

                    b.Property<string>("LeadTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxDistance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("OriginLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeliveryDetailId");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("DeliveryDetails");
                });

            modelBuilder.Entity("MarketPrice.Models.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<byte>("LocationTypeId")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("Town", "Region")
                        .IsUnique();

                    b.ToTable("Locations", t =>
                        {
                            t.HasCheckConstraint("CK_Locations_Region_Enum", "[Region] BETWEEN 0 AND 9");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.LocationType", b =>
                {
                    b.Property<byte>("LocationTypeId")
                        .HasColumnType("tinyint");

                    b.Property<int>("LocationTypeName")
                        .HasColumnType("int");

                    b.HasKey("LocationTypeId");

                    b.ToTable("LocationTypes", t =>
                        {
                            t.HasCheckConstraint("CK_LocationTypes_LocationTypeName_Enum", "[LocationTypeName] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.Position", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("PositionTypeId")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PositionId");

                    b.HasIndex("CommodityId");

                    b.HasIndex("PositionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Positions", t =>
                        {
                            t.HasCheckConstraint("CHK_Positions_Status", "[Status] IN (N'Opened', N'Closed', N'Cancelled')");

                            t.HasCheckConstraint("CK_Positions_Status_Enum", "[Status] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.PositionType", b =>
                {
                    b.Property<byte>("PositionTypeId")
                        .HasColumnType("tinyint");

                    b.Property<int>("PositionTypeName")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.HasKey("PositionTypeId");

                    b.ToTable("PositionTypes", t =>
                        {
                            t.HasCheckConstraint("CHK_PositionTypes_PositionTypeName", "[PositionTypeName] IN (N'Bid', N'Offer')");

                            t.HasCheckConstraint("CK_PositionTypes_PositionTypeName_Enum", "[PositionTypeName] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RaterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.HasKey("RatingId");

                    b.HasIndex("RaterUserId");

                    b.HasIndex("RatedUserId", "RaterUserId");

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("CHK_Ratings_Score", "[Score] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("UnitOfMeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitOfMeasureCodeEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureCodeFrench")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasureNameFrench")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitOfMeasureId");

                    b.ToTable("UnitOfMeasures");
                });

            modelBuilder.Entity("MarketPrice.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPremiumUser")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("IdCardNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MarketPrice.Models.Verification", b =>
                {
                    b.Property<Guid>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VerificationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VerificationId");

                    b.HasIndex("UserId");

                    b.HasIndex("VerificationTypeId");

                    b.ToTable("Verifications", t =>
                        {
                            t.HasCheckConstraint("CHK_Verifications_Status", "[Status] IN (N'Pending', N'Unverified', N'Redo', N'Verified', N'Rejected')");

                            t.HasCheckConstraint("CK_Verifications_Status_Enum", "[Status] BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("MarketPrice.Models.VerificationType", b =>
                {
                    b.Property<Guid>("VerificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VerificationTypeName")
                        .HasColumnType("int");

                    b.HasKey("VerificationTypeId");

                    b.ToTable("VerificationTypes", t =>
                        {
                            t.HasCheckConstraint("CHK_VerificationTypes_VerificationTypeName", "[VerificationTypeName] IN (N'IdCardNumber', N'Email', N'PhoneNumber')");

                            t.HasCheckConstraint("CK_VerificationTypes_VerificationTypeName_Enum", "[VerificationTypeName] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("LocationUser", b =>
                {
                    b.HasOne("MarketPrice.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Commodity", b =>
                {
                    b.HasOne("MarketPrice.Models.CommodityType", null)
                        .WithMany()
                        .HasForeignKey("CommodityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.CommodityType", b =>
                {
                    b.HasOne("MarketPrice.Models.CommodityGroup", null)
                        .WithMany()
                        .HasForeignKey("CommodityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("DefaultUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.DeliveryDetail", b =>
                {
                    b.HasOne("MarketPrice.Models.Position", null)
                        .WithOne()
                        .HasForeignKey("MarketPrice.Models.DeliveryDetail", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Location", b =>
                {
                    b.HasOne("MarketPrice.Models.LocationType", null)
                        .WithMany()
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Position", b =>
                {
                    b.HasOne("MarketPrice.Models.Commodity", null)
                        .WithMany()
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.PositionType", null)
                        .WithMany()
                        .HasForeignKey("PositionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Rating", b =>
                {
                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RatedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RaterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.User", b =>
                {
                    b.HasOne("MarketPrice.Models.AccountType", null)
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketPrice.Models.Verification", b =>
                {
                    b.HasOne("MarketPrice.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPrice.Models.VerificationType", null)
                        .WithMany()
                        .HasForeignKey("VerificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
